### ISSUE TITLE
Failing to create fundraising pages for some users

### ISSUE THREAD

**Issue by mwillmott** [Techbikers/client#1]
There is an incredibly irritating bug which is causing the creation of _most_ fundraising pages to fail. This happens when a user has a different email address on their Just Giving account to their TechBikers account.

When the email addresses are the same, Auth0 (our authentication broker) links the two accounts enabling the TechBiker user that is registered for the ride to use the JustGiving `access_token` to create a fundraising page on their behalf.

If the email addresses are different then we effectively end up with two user accounts. The flow is such that the "new" JustGiving user account is the one that attempts to create the fundraising page, but gets a 401 Unauthorised because that user isn't actually registered on the ride.

The fix needs to be either:
- linking the two accounts regardless of email address (which would introduce the idea that a TechBikers account can have more than one email address linked to it)
- don't return the "new" user but make sure we can still use the `access_token`. Not entirely sure what this would look like.

**Comment by mwillmott** [comment]
This might shed a bit more light into how we create fundraising pages.

![techbikers_ creating a fundraising page](https://user-images.githubusercontent.com/2144739/44618429-7dc89880-a86d-11e8-89b6-3a0ce8c1a233.png)

**Comment by mwillmott** [comment]
@jlampa i agree that we don't need to link the JustGiving identity to the user account (which is the cause of this bug). We don't need to save the access token at all in fact as we're not planning on using it beyond creating the fundraising page in JustGiving. I propose we rework the logic to the following flow:
![TechBikers Fundraising Setup](https://user-images.githubusercontent.com/2144739/54225609-02ba8d00-44f4-11e9-84db-e30fd4f91c31.png)

**Comment by jlampa** [comment]
Yup, that's exactly what I had in mind.

> --


JL

**Comment by mwillmott** [comment]
Great! I've got some time i can spend on this tonight. I'll tackle the changes in the client app to begin with. Let me know if you have any time to get stuck in and where.
